Updating Dockerfile (#52)
* Cleanup

* Adding benchmark scripts

Co-authored-by: Yaswant Vishwakarma <yvishwa@microsoft.com>

diff --git a/spark/Dockerfile b/spark/Dockerfile
--- a/spark/Dockerfile
+++ b/spark/Dockerfile
@@ -2,19 +2,36 @@
 # Licensed under the MIT license.
 
 # Base Image
-FROM java:openjdk-8-jdk
+FROM openjdk:8-jre-slim
 
 # Define Spark and Hadoop Verson
-ENV HADOOP_VERSION 3.2.0
+ENV HADOOP_VERSION 3.3.0
 ENV HADOOP_SHORT_VERSION 3.2
 ENV SPARK_VERSION 3.0.0
 ENV OPENSSL_VERSION 1.1.0
 ENV SPARK_HOME=/opt/spark
 ENV PATH=$PATH:$SPARK_HOME/bin
+
+
 ENV HADOOP_HOME=/opt/hadoop
 ENV PATH=$PATH:$HADOOP_HOME/bin
+
+
 ENV LD_LIBRARY_PATH=$HADOOP_HOME/lib/native
 ENV HADOOP_OPTIONAL_TOOLS="hadoop-azure,hadoop-azure-datalake"
+
+# Update Environment
+RUN set -ex && \
+    sed -i 's/http:/https:/g' /etc/apt/sources.list && \
+    apt-get update && \
+    ln -s /lib /lib64 && \
+    apt-get upgrade -y && \
+    apt install -y bash tini libc6 libpam-modules krb5-user libnss3 curl && \
+    rm /bin/sh && \
+    ln -sv /bin/bash /bin/sh && \
+    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
+    chgrp root /etc/passwd && chmod ug+rw /etc/passwd && \
+    rm -rf /var/cache/apt/*
 
 
 # Download and install haddop
@@ -25,7 +42,6 @@ RUN mkdir -p /opt && \
     ln -s hadoop-${HADOOP_VERSION} hadoop && \
     rm hadoop-${HADOOP_VERSION}.tar.gz && \
     echo Hadoop ${HADOOP_VERSION} native libraries installed in /opt/hadoop/lib/native
-
 
 # Download and install spark
 RUN mkdir -p /opt && \
@@ -41,10 +57,8 @@ RUN mkdir -p /opt && \
 RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/${HADOOP_VERSION}/hadoop-azure-${HADOOP_VERSION}.jar -o /opt/spark/jars/hadoop-azure-${HADOOP_VERSION}.jar
 RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure-datalake/${HADOOP_VERSION}/hadoop-azure-datalake-${HADOOP_VERSION}.jar -o /opt/spark/jars/hadoop-azure-datalake-${HADOOP_VERSION}.jar
 
-
 # Download and install OpenSSL library
 RUN curl https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/${OPENSSL_VERSION}.Final/wildfly-openssl-${OPENSSL_VERSION}.Final.jar -o /opt/spark/jars/wildfly-openssl-${OPENSSL_VERSION}.Final.jar
-
 
 # add benchmark code 
 ADD tpcds_jars /opt/spark/jars
@@ -53,14 +67,21 @@ ADD tpcds_jars /opt/spark/jars
 RUN mkdir /opt/tpcds-kit/
 RUN mkdir /opt/tpcds-kit/tools
 
+#Spark work directory
+RUN mkdir /opt/spark/work-dir 
+
 ADD tpcds-kit/tools /opt/tpcds-kit/tools
+RUN chmod +x /opt/tpcds-kit/tools/checksum /opt/tpcds-kit/tools/dsdgen /opt/tpcds-kit/tools/dsqgen /opt/tpcds-kit/tools/mkheader
+RUN chmod +x /opt/tpcds-kit/tools/distcomp
+
+#ADD start-common.sh common.sh start-master start-worker /opt/
+#RUN chmod +x /opt/start-common.sh /opt/start-master /opt/start-worker
 
 # add scripts and update spark default config
-ADD start-common.sh common.sh start-master start-worker /opt/
 ADD spark-defaults.conf /opt/spark/conf/spark-defaults.conf
 ADD core-site.xml /opt/spark/conf/core-site.xml
+
 ENV PATH $PATH:/opt/spark/bin
-RUN chmod +x /opt/start-common.sh /opt/start-master /opt/start-worker
 
 COPY entrypoint.sh /opt/entrypoint.sh
 COPY start-spark.sh start-spark.sh
